### PR TITLE
Various improvements including affine inverse

### PR DESCRIPTION
**Pull request by mhosken**
Various little bits of goodness to improve support parity for line, point and quadraticbeziers. Moved pyclipper to non-essential requirement.

### CODE REVIEW

**Comment by simoncozens** [comment]
Looks good to me. I am not sure why we need to bring `Point`s up to parity with `Segment`s - they're separate levels of abstraction and I would have thought it would be better to ensure that they *don't* get mixed together - but I am going to trust that you know what you're doing. :-) Thanks.

**Comment by simoncozens** [comment]
You mention making pyclipper non-essential, but I don't see code which does that.

**Comment by mhosken** [comment]
Not trying to bring Point up parity with Segment. But if a point can have an angle, it can have a slope.

Yeh forgot to move the import pyclipper into the clip function. Am ambivalent since the target core purpose of the library is clip() (not that I am using it that way).

**Comment by anthrotype** [comment]
(shameless plug) You guys may also want to have a look at https://github.com/fonttools/skia-pathops if you are interested in a clipping library that works directly on Bézier curves, not just polygons.

**Pull request merged**
